### ISSUE TITLE
Worker service account not set properly

### ISSUE THREAD

**Issue by thomastaylor312** [Azure/brigade#155]
Worker pods spun up by the controller are not using the `brigade-worker` service account. Talking over the issue with @technosophos, he said that the worker will spin up jobs with the proper service account, but the worker itself does not.

Example from one of my jobs (some parts redacted or removed for sizing):
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2017-11-17T23:12:22Z
  labels:
    build: 01bz6426m7nzer4pdgbcnyq0dq
    commit: ad9ed7fdd9837d9b974f71a2170cdbc9764f48dc
    component: build
    heritage: brigade
    project: brigade-0fb34102a8978e5103c27b44c6f499610bf3f70fcf7ef19def6a31
  name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
  namespace: brigade-test
spec:
  containers:
  - command:
    - yarn
    - start
    env:
    - name: BRIGADE_PROJECT_ID
      valueFrom:
        secretKeyRef:
          key: project_id
          name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
    - name: BRIGADE_EVENT_TYPE
      valueFrom:
        secretKeyRef:
          key: event_type
          name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
    - name: BRIGADE_EVENT_PROVIDER
      valueFrom:
        secretKeyRef:
          key: event_provider
          name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
    - name: BRIGADE_BUILD_ID
      valueFrom:
        secretKeyRef:
          key: build_id
          name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
    - name: BRIGADE_COMMIT
      valueFrom:
        secretKeyRef:
          key: commit
          name: test-01bz6426m7nzer4pdgbcnyq0dq-ad9ed7fd
    - name: BRIGADE_PROJECT_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: brigade-worker:test
    imagePullPolicy: Always
    name: brigade-runner
    volumeMounts:
    - mountPath: /etc/brigade
      name: brigade-build
      readOnly: true
    - mountPath: /vcs
      name: vcs-sidecar
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-test1
      readOnly: true
  restartPolicy: Never
  serviceAccount: default
  serviceAccountName: default
```

**Comment by technosophos** [comment]
Yeah, it should look like this:

```
 restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: brigade-worker
  serviceAccountName: brigade-worker
  terminationGracePeriodSeconds: 30
  volumes:
  - name: brigade-build
    secret:
      defaultMode: 420
      secretName: brigade-worker-01bz65k7f2cz9z282y38j897tm-master
  - emptyDir: {}
    name: vcs-sidecar
  - name: brigade-worker-token-fc8vg
    secret:
      defaultMode: 420
      secretName: brigade-worker-token-fc8vg
status:
```
