### ISSUE TITLE
Service account per Job

### ISSUE THREAD

**Issue by mumoshu** [Azure/brigade#251]
I'd wanted to associate a service account with enough permissions to deploy things to k8s, only to the job runs a k8s deployment.

However, as far as I can see from code, [brigade seems to hard-code `brigade-worker` serviceaccount to be used by all the job runner pod](https://github.com/Azure/brigade/blob/8346887653a41ca7879801e64d1f3f20561273b6/brigade-worker/src/k8s.ts#L585). It would be great if it could be overridden like `job.serviceaccount = "deployer"` in brigade.js for this use-case.

**Comment by wstrange** [comment]
I think that running kubectl , Helm, etc. from within Jobs will be very common.

**Comment by mumoshu** [comment]
Thanks for the response!

Regarding kubectl, Yes - that's why this could be important.

Not sure about helm though. AFAIK tiller rather than helm is responsible to manage k8s resources. The serviceaccout associated to the pod running helm won't be used by tiller(at least for now). We'd need to have tiller-per-ns instead.

**Comment by technosophos** [comment]
The one thing I am worried about is whether that would open up a security hole. Are there cases where the script could then grant a Job a higher level of permissions then it is supposed to have?

I am not entirely clear about what restrictions Kubernetes puts on the serviceaccount part of a pod definition. If we can do this without the risk of a script being able to escalate privileges, I'd be happy to implement this feature.

**Comment by mumoshu** [comment]
@technosophos Thanks for the response!

> I am not entirely clear about what restrictions Kubernetes puts on the serviceaccount part of a pod definition. 

AFAIK, RBAC can't be used for restricting which serviceaccount can be referred via the `serviceAccountName` field in a pod spec. An user who has permissions to "create pods" is able to mount any serviceaccount token to a pod. Try:

```yaml
# rbac.yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: foo-pod-all
subjects:
- kind: ServiceAccount
  name: foo
roleRef:
  kind: ClusterRole
  name: pod-all
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pod-all
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
```

```
$ ns=yourns

$ alias k="kubectl --namespace $ns"

$ another_sa=<any sa shown by running `kubectl get sa`>

$ k create sa foo

$ k apply -f rbac.yaml

$ k  run --restart=Never --as system:serviceaccount:$ns:foo --image alpine:edge -it --overrides="$(jq -n '{spec:{serviceAccountName:"$another_sa"}}')" mytestpod -- uptime
rolebinding "foo-pod-all" configured
clusterrole "pod-all" configured
 04:10:35 up 76 days, 21:14,  load average: 0.41, 0.16, 0.11

# verify that the serviceaccountname does exist in the pod spec
$ k get po mytestpod -o yaml
```

>  If we can do this without the risk of a script being able to escalate privileges

Assuming RBAC doesn't work in this case as above, I guess a whitelist of allowed serviceaccount per brigade project, which is an empty list by default, would work.

```yaml
allowedServiceAccounts:
- deployer-sa
```

```js
events.on('push', (e, p) => {
  const job = new Job(...)
  job.serviceAccount = "deployer-sa"
  job.run()
})
```
