### ISSUE TITLE
Helm Configurable LivenessProbe Settings

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [Azure/brigade#268]
Please make the livenessProbe settings such as:

```
periodSeconds
initialDelaySeconds
timeoutSeconds
```

configurable through helm values.

**Comment by mumoshu** [comment]
@brandon-bethke-neudesic Hi! Which pod would you like to customize with those settings? There are brigade, brigade-project, brigade-worker and so on.

**Comment by brandon-bethke-neudesic** [comment]
Every pod that requires a liveness probe.

**Comment by mumoshu** [comment]
@brandon-bethke-neudesic Thanks! Would you mind clarifying why you need tweak those on every pod?
I'm asking because there seems like no user configurable liveness probe for any brigade-related pod and the default liveness probes isn't that unreliable or slow.
Are you seeing specific errors?

**Comment by mumoshu** [comment]
@brandon-bethke-neudesic Thanks! Would you mind clarifying why you need tweak those on every pod?
I'm asking because there seems like no user configurable liveness probe for any brigade-related pod and the default liveness probes isn't that unreliable or slow.
Are you seeing specific errors?

**Comment by brandon-bethke-neudesic** [comment]
Not all environments are created equal and in my sad little world the default probe settings are not appropriate. The Pods are restarting a hundred times a day needlessly and simply because the vm is a little constrained.

If cluttering up the values.yaml with too many options is a concern, then perhaps just use a default in the helm *-deployment.yaml files so the value doesn't need to be explicitly specified. There are just optional settings after all. 

Example: 

```
livenessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.api.service.internalPort }}
  periodSeconds: {{ default 20 .Values.api.service.livenessPeriodSeconds }}
  initialDelaySeconds: {{ default 40 .Values.api.service.livenessInitialDelaySeconds }}
  timeoutSeconds: {{ default 5 .Values.api.service.livenessTimeoutSeconds }}
```
