### ISSUE TITLE
Allow Annotation of Worker Pods

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#421]
We use [kube2iam](https://github.com/jtblin/kube2iam) to manage the roles assumed by our services. This is used along with KMS keys to allow pods to decrypt secrets. We'd prefer to use this method, opposed to Brigade Secrets + injecting secrets via the Job ENV variable.

To accomplish this, we'd need to be able to pass an annotation to at least the Job pods. In straight-up k8s it would look something like this ([docs](https://github.com/jtblin/kube2iam#kubernetes-annotation)):

```
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: role-arn
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "some-bucket"
    name: aws-cli
```

I think we could go a couple of ways with this:

## Define at the Project Level
This would expose the option on the deployed `brigade/brigade-project` values.yml file. I think in this case, the worker and all jobs would get this annotation.

## Define on the `new Job` in JS
This would define per-pod job. e.g.

```javascript
let job = new Job('something', 'someimage');
job.annotations = {  'iam.amazonaws.com/role': 'role-arn' };
```

Thoughts?
