### ISSUE TITLE
VACUUM_MAX_BUILDS variable not honoured

### ISSUE THREAD

**Issue by Abulfat** [Azure/brigade#576]
Latest brigade helm release
Docker image: deis/brigade-vacuum:v0.15.0

We noticed that VACUUM_MAX_BUILDS env variable is ignored by vacuum. Although VACUUM_AGE variable gets picked up as expected.

We tested both maxBuilds() and getAge() functions with both env variables against custom docker image and both return values.
(https://github.com/Azure/brigade/blob/master/brigade-vacuum/cmd/brigade-vacuum/commands/app.go)

We suspect the issue around deis/brigade-vacuum:v0.15.0 image.

Please let us know if you need further information.

Thanks

**Comment by technosophos** [comment]
Can you give me an example of what you tested? I'm looking through the code in the `vacuum` package, but not entirely sure what I am looking for.

**Comment by Abulfat** [comment]
Here is the sample go where I am testing vacuum's functions responsible for handling those two ENV variables:

```package main

import (
	"fmt"
	"os"
        "strconv"
)

const (
	envMaxBuilds  = "VACUUM_MAX_BUILDS"
	envAge        = "VACUUM_AGE"
)

var (
	globalMaxBuilds  = -1
	globalAge        = ""
)

func maxBuilds() int {
	if globalMaxBuilds > -1 {
		return globalMaxBuilds
	}
	v, ok := os.LookupEnv(envMaxBuilds)
	if !ok {
		return 0
	}
	m, err := strconv.Atoi(v)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Ignoring non-int value %q", v)
		return 0
	}
	return m
}

func getAge() string {
	if globalAge != "" {
		return globalAge
	}
	return os.Getenv(envAge)
}

func main() {
  a := getAge()
  mb := maxBuilds()
  if mb == 0 {
      fmt.Printf("VACUUM_MAX_BUILDS is not set\n")
  } else {
      fmt.Printf("VACUUM_MAX_BUILDS is set:  %d\n", mb) 
  }
   if a == "" {
      fmt.Printf("VACUUM_AGE is not set\n")
  } else {
      fmt.Printf("VACUUM_AGE is set:  %s\n", a)
  }
   
}
```

I am testing that piece of Go with a sample cronjob below:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: test-brigade-brigade
    chart: brigade-0.15.0
    heritage: Tiller
    release: test-brigade
    role: vacuum
  name: test-brigade-brigade-vacuum
  namespace: test
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: test-brigade-brigade
            role: vacuum
        spec:
          containers:
          - env:
            - name: VACUUM_MAX_BUILDS
              value: "10"
            - name: VACUUM_AGE
              value: "500h"
            - name: BRIGADE_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            image: golang:alpine
            args:
            - sleep
            - "600"
            imagePullPolicy: IfNotPresent
            name: brigade-vacuum
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: test-brigade-brigade-vacuum
          serviceAccountName: test-brigade-brigade-vacuum
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 10
  suspend: false
```

As you can see, I pass two ENV variables to pod and when I run Go code above inside the pod manually, it prints out both variables. However, when I set those variables in Brigade's values.yaml, seems only VACUUM_AGE gets picked up.

```
vacuum:
  enabled: true
  # Set a schedule for how frequently this check is run.
  # Note that a run of the vacuum typically takes at least a minute. Finer-level
  # granularity than that may result in multiple vacuums running at once.
  # Format follows accepted Cron formats: https://en.wikipedia.org/wiki/Cron
  schedule: "@hourly"
  registry: "deis"
  name: "brigade-vacuum"
  # tag: latest
  # Age tells the vacuum how old a thing may be before it is considered ready to
  # be vacuumed. The format is an integer followed by the suffix h (hours), m (minutes)
  # or s (seconds).
  # The default is 30 days (720 hours)
  age: "720h"
  # maxBuilds tells the vacuum what the absolute maximum number of builds may be stored
  # at a time. Where possible, we recommend using age rather than builds.
  # 0 means no limit is imposed.
  #
  # If both age and maxBuilds are provided, age is applied first, then maxBuilds.
  maxBuilds: 10
```

I also noticed you use different os calls to fetch those ENV variables (os.LookupEnv, os.Getenv)
The only difference between my example and vacuum is the underlying docker image.
